---
title: "Group 06 CA pollution burden"
author: "Elijah Baker & Deanna Mireles"
date: "11/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)
```

```{r}
library(here)
library(janitor)
library(tidyverse)
```


```{r}
ces<- read_csv(here("data", "ces3demographics.csv")) %>%
  clean_names()
```


```{r fig.cap="Figure 1. A hexplot showing the relationship between environmental pollution and percent white populaiton, where a higher CalEnviroScreen 3.0 score indicates greater environmental pollution."}
ggplot(data = ces, 
       aes(x = white_percent, 
           y = ces_3_0_score)) +
  geom_hex() +
  scale_fill_gradient(low = "black", 
                      high = "blue")+
  theme_minimal() +
  labs(x="Percent of white-identifying individuals",
       y= "CalEnviroScreen 3.0 score",
       title= "CalEnviroScreen 3.0 Score Compared With Precentage of White-idenitfied Individuals")

```

The overall trend we can observe is that as white-identifying populations reach approximately 75%, they experience low CalEnviroScreen scores between 5-15; whereas white-identifying populations closer to 0% experience a greater likelihood of scores between 45-55.

## Citation

Office of Environmental Health Hazard Assessment. “CalEnviroScreen 3.0.” Oehha.ca.gov, June 2018, https://oehha.ca.gov/calenviroscreen/report/calenviroscreen-30. 
